### ISSUE TITLE
what is the motive?

### ISSUE THREAD

**Issue by utkarshchandrakar** [siddharthshah3030/guesscolor#2]
What we are going to do with finding RGB combinations

**Comment by siddharthshah3030** [comment]
### invalid issue
_seems you did not even go through the project ?_
It's a game where you are given RGB value of a colour and you have to guess it from visuals 
even choose difficulty and play it again with new combinations

**Comment by siddharthshah3030** [comment]
### motive : 
it checks how good are your skills at understanding RGB values of colours and It's visuals

**Comment by siddharthshah3030** [comment]
[this](https://github.com/siddharthshah3030/guesscolor/commit/320dc8861959353705a6728489ccabc28e170485) commit solves your issue
